/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.carsystem;

/**
 *
 * @author thuy
 */
public class SearchScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    public SearchScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ManufacturerComboBox = new javax.swing.JComboBox<>();
        YearComboBox = new javax.swing.JComboBox<>();
        SearchButton = new javax.swing.JButton();
        ModelTextField = new javax.swing.JTextField();
        PriceComboBox = new javax.swing.JComboBox<>();
        KilometerComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 17)); // NOI18N
        jLabel1.setText("SEARCH");

        jLabel3.setText("Price");

        jLabel4.setText("Manufacturer");

        jLabel5.setText("Kilometer");

        jLabel6.setText("Model");

        jLabel7.setText("Year");

        ManufacturerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Honda", "Toyota", "Tesla", "Mazda", "Lexus", "Ford", "Other" }));
        ManufacturerComboBox.setName("manufacturerCombo"); // NOI18N
        ManufacturerComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManufacturerComboBoxActionPerformed(evt);
            }
        });

        YearComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", " " }));

        SearchButton.setText("Search");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        PriceComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5001-10000", "10001-15000", "15001-20000", "20001-25000", "25001-30000", "30001-35000", "35001-40000", "40001-45000", "45001-50000", "50001-55000", "55001-60000", "60001-65000", "65001+" }));
        PriceComboBox.setName("manufacturerCombo"); // NOI18N
        PriceComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PriceComboBoxActionPerformed(evt);
            }
        });

        KilometerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1-10000", "10001-20000", "20001-30000", "30001-40000", "40001-50000", "50001-60000", "60001-70000", "70001+" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ModelTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ManufacturerComboBox, 0, 152, Short.MAX_VALUE)
                            .addComponent(YearComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PriceComboBox, 0, 152, Short.MAX_VALUE)
                            .addComponent(KilometerComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ManufacturerComboBox))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ModelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(YearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(PriceComboBox))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(KilometerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(SearchButton)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        // TODO add your handling code here:
        String manufacturer = (String) ManufacturerComboBox.getSelectedItem();
        String model = ModelTextField.getText();
        String year = (String) YearComboBox.getSelectedItem();
        String price = (String) PriceComboBox.getSelectedItem();
        String kilometer = (String) KilometerComboBox.getSelectedItem();
       
        System.out.println(manufacturer);
        
        SearchResultsScreen resultScreen = new SearchResultsScreen();
        resultScreen.setVisible(true);
        resultScreen.setSearchResult(CarManager.sharedInstance.getCarsByMake(manufacturer));
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void ManufacturerComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManufacturerComboBoxActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ManufacturerComboBoxActionPerformed

    private void PriceComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PriceComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PriceComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CarManager.sharedInstance.addCar(new Car("Tesla", "Model S", "", "2021", 75000, 10, "TSLAMS001", ""));
                CarManager.sharedInstance.addCar(new Car("Tesla", "Model 3", "", "2021", 175000, 10, "TSLAM3001", ""));
                CarManager.sharedInstance.addCar(new Car("Honda", "Civic", "", "2020", 25000, 50, "HNDCV20001", "Honda Civic"));
                CarManager.sharedInstance.addCar(new Car("Honda", "CRV", "", "2018", 30000, 30, "HNDCRV18001", "Honda CRV"));
                CarManager.sharedInstance.addCar(new Car("Mazda", "CX5", "", "2020", 10000, 10, "KIAMN16001", "This is the old car"));
                
                new SearchScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> KilometerComboBox;
    private javax.swing.JComboBox<String> ManufacturerComboBox;
    private javax.swing.JTextField ModelTextField;
    private javax.swing.JComboBox<String> PriceComboBox;
    private javax.swing.JButton SearchButton;
    private javax.swing.JComboBox<String> YearComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
